using Vali_Flow.Sql.Builder;

namespace Vali_Flow.Sql.Dialects;

/// <summary>SQL dialect for Oracle Database 12c+.</summary>
public sealed class OracleDialect : ISqlDialect
{
    /// <inheritdoc/>
    public string ParameterPrefix => ":";
    /// <inheritdoc/>
    public string LikeOperator => "LIKE";
    /// <inheritdoc/>
    public string TrueValue => "1";
    /// <inheritdoc/>
    public string FalseValue => "0";
    /// <inheritdoc/>
    public string DialectName => "Oracle";
    /// <summary>Oracle supports the MERGE statement.</summary>
    public bool SupportsMerge => true;
    /// <summary>
    /// Oracle does not support <c>WHEN NOT MATCHED BY TARGET</c> syntax.
    /// Only <c>WHEN NOT MATCHED</c> is valid in Oracle MERGE statements.
    /// </summary>
    public bool SupportsMergeNotMatchedByTarget => false;
    /// <summary>
    /// Oracle uses <c>RETURNING col INTO :var</c> which is incompatible with the
    /// PostgreSQL-style <c>RETURNING</c> clause generated by the builder.
    /// </summary>
    public bool SupportsReturning => false;
    /// <summary>Oracle natively supports NULLS FIRST / NULLS LAST in ORDER BY.</summary>
    public bool SupportsNullsOrdering => true;
    /// <summary>Oracle supports <c>FOR UPDATE</c> for exclusive row locking.</summary>
    public string ForUpdateClause => "FOR UPDATE";
    /// <inheritdoc/>
    public string CurrentTimestamp => "SYSDATE";
    /// <summary>Oracle does not require the RECURSIVE keyword for recursive CTEs.</summary>
    public string RecursiveCteKeyword => string.Empty;
    /// <summary>Oracle's OFFSET/FETCH syntax requires ORDER BY even when only TAKE is specified.</summary>
    public bool RequiresOrderByForTakeOnly => true;

    /// <inheritdoc/>
    public string QuoteIdentifier(string name) => $"\"{name}\"";

    /// <inheritdoc/>
    public string NullCheck(string columnSql) => $"{columnSql} IS NULL";

    /// <inheritdoc/>
    public string NotNullCheck(string columnSql) => $"{columnSql} IS NOT NULL";

    /// <inheritdoc/>
    public string ILikeExpression(string columnSql, string parameterName)
        => $"UPPER({columnSql}) LIKE UPPER({parameterName})";

    /// <summary>Oracle does not use TOP; uses FETCH NEXT instead.</summary>
    public string SelectTop(int? take) => string.Empty;

    /// <summary>Oracle 12c+ pagination using OFFSET ... ROWS FETCH NEXT ... ROWS ONLY.</summary>
    public string LimitOffset(int? take, int? skip)
    {
        int offset = skip ?? 0;
        if (take.HasValue && offset > 0)
            return $"OFFSET {offset} ROWS FETCH NEXT {take} ROWS ONLY";
        if (take.HasValue)
            return $"OFFSET 0 ROWS FETCH NEXT {take} ROWS ONLY";
        if (offset > 0)
            return $"OFFSET {offset} ROWS";
        return string.Empty;
    }

    /// <summary>Oracle uses <c>EXTRACT(part FROM column)</c> for date part extraction.</summary>
    public string DatePartExpression(string columnSql, string part)
        => $"EXTRACT({part.ToUpperInvariant()} FROM {columnSql})";

    /// <summary>Returns "NULLS FIRST", "NULLS LAST", or empty string for Default.</summary>
    public string NullsOrderClause(NullsOrder nulls) => nulls switch
    {
        NullsOrder.First => "NULLS FIRST",
        NullsOrder.Last  => "NULLS LAST",
        _                => string.Empty
    };

    /// <summary>Oracle uses <c>||</c> for string concatenation.</summary>
    public string ConcatExpression(params string[] parts)
        => string.Join(" || ", parts);

    /// <summary>
    /// Oracle does not accept AS before the target alias in MERGE INTO syntax.
    /// Syntax: MERGE INTO table alias USING ... (no AS keyword).
    /// </summary>
    public string MergeTargetAlias(string alias) => alias;

    /// <summary>Oracle uses LENGTH() instead of LEN().</summary>
    public string StringLengthExpression(string column) => $"LENGTH({column})";

    /// <summary>Oracle uses INSTR(column, search) - 1 for 0-based index-of (arguments are inverted vs CHARINDEX).</summary>
    public string IndexOfExpression(string searchParam, string column)
        => $"INSTR({column}, {searchParam}) - 1";

    /// <summary>Oracle uses CEIL() instead of CEILING().</summary>
    public string CeilingExpression(string column) => $"CEIL({column})";

    /// <summary>Oracle requires an ESCAPE clause for LIKE patterns with special characters.</summary>
    public string LikeEscapeClause() => " ESCAPE '\\'";

    /// <summary>
    /// Oracle does not have a DATEADD() function.
    /// Use interval arithmetic directly in raw SQL (e.g. col + INTERVAL '1' DAY).
    /// </summary>
    public string DateAddExpression(string datePart, string amount, string column)
        => throw new NotSupportedException(
            "DateAdd is not supported for OracleDialect. Use raw SQL interval arithmetic instead (e.g. col + INTERVAL '1' DAY).");
}
